add: clone sap-styleguides repo
RizInno/btp-best-practices pull request #1
Opened 2023-10-18 16:13 UTC by melissaxd96

- clone sap-styleguides repo

2023-10-19 06:34 UTC, jcailan requested changes
PR description -- this is not an sbb project.

2023-10-19 06:34 UTC, jcailan commented on CODEOWNERS
> +# global owners as fallback for anything not matched below
just replace everything with

`* @jcailan`

2023-10-19 06:34 UTC, jcailan commented on README.md
>  Rizing Innovation Best Practices
Just remove the first 2 lines for now

2023-10-19 06:41 UTC, jcailan requested changes

2023-10-19 06:41 UTC, jcailan commented on clean-abap/RAP.md
> +## Content
Remove `RAP.md` since needs rework.

2023-10-19 10:02 UTC, melissaxd96 commented on clean-abap/RAP.md
> +## Content
this is done

2023-10-19 10:38 UTC, jcailan submitted a review, later dismissed

2023-10-20 05:26 UTC, jcailan approved these changes

2023-10-21 07:20 UTC, closed without merging